apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-core
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/eskillarsen/platform-1.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: "argocd"
    spec:
      project: "my-project"
      source:
        repoURL: https://github.com/eskillarsen/platform-1.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
